# Tell Spring where your MySQL database is
spring.datasource.url=jdbc:mysql://localhost:3306/ticket_booking
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# Tell Spring to auto-create tables from our Java classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT settings
jwt.secret=ThisIsASecretKeyForJWTMustBeLongEnough123456
jwt.expiration=86400000
spring.jpa.open-in-view=false
